# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
#
# Based on:
# https://github.com/mpnunez/pybind11-conan-example/blob/a259bfe9bd99ded80f4bf16ce7c639e140f26408/.pre-commit-config.yaml
repos:
# Standard hooks
# - repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v3.2.0
#   hooks:
#   - id: check-yaml
#   - id: end-of-file-fixer
#   - id: mixed-line-ending
#   - id: trailing-whitespace
#   - id: fix-encoding-pragma

# Black, the code formatter, natively supports pre-commit
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    exclude: ^.github/$

